directory: ~/Music
library: ~/.config/beets/library.db
pluginpath:
  - ~/.config/beets/beetsplug

plugins: [
  inline,
  embedart,
  edit,
  ftintitle,
  # wlg,
  lastgenre,
  events,
  diverse,
  discogs,
  convert,
  info,
  fetchart,
  bandcamp
  ]

item_fields:
  multidisc: 1 if disctotal > 1 else 0
  disc_and_track: u'%02i.%02i.' % (disc, track) if disctotal > 1 else u'%02i.' % (track)

ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: white
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue

import:
  move: true

discogs:
  user_token: iimDVRTeBoVDcpBymdUsCtxjSRqJHMZTEUbRaLcN

wlg:
  auto: yes
  force: no

convert:
  formats:
    mp3: ffmpeg -i $source -y -vn -aq 0 $dest

edit:
  itemfields: track title composer artist album event
  albumfields: album albumartist event

format_album: $albumartist - $album%ifdef{event, (%ifdef{event}), ($year)}

bandcamp:
  art: true

paths:
  default: $albumartist/%if{$catalognum,[$catalognum] }$album%ifdef{event, (%ifdef{event}), ($year)}/%if{$multidisc,Disc $disc/}$disc_and_track $artist - $title
  comp: $label/%if{$catalognum,[$catalognum] }$album%ifdef{event, (%ifdef{event}), ($year)}/%if{$multidisc,Disc $disc/}$disc_and_track $artist - $title
